### ISSUE TITLE
Bug reports where the cause could not be found

### ISSUE THREAD

**Issue by ainlzj** [brachy84/InventoryBogoSorter#1]
[crash-2022-06-17_11.17.12-client.txt](https://github.com/brachy84/InventoryBogoSorter/files/8932798/crash-2022-06-17_11.17.12-client.txt)

**Comment by brachy84** [comment]
You don't have this mod installed.

**Comment by xemnes** [comment]
`java.lang.NoClassDefFoundError: toughasnails/api/config/ISyncedOption

	at blockynoob.waterskin.client.ClientProxy.<init>(ClientProxy.java:22)`

the crash is because you dont have tough as nails installed, which waterskin needs to work.

**Comment by ainlzj** [comment]
Sorry, I sent the wrong file le

**Comment by ainlzj** [comment]
[crash-2022-06-19_09.08.47-server.txt](https://github.com/brachy84/InventoryBogoSorter/files/8934579/crash-2022-06-19_09.08.47-server.txt)

**Comment by brachy84** [comment]
Ah ok thanks. A lot of things will change in the next update, so this crash will be fixed
